# Generated by Django 2.2.5 on 2019-11-29 20:49

from django.db import migrations, models
import talentaMed.apps.localidades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, validators=[talentaMed.apps.localidades.models._codigo_simple_validator], verbose_name='Código')),
                ('texto', models.CharField(max_length=30, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, validators=[talentaMed.apps.localidades.models._codigo_simple_validator], verbose_name='Código')),
                ('texto', models.CharField(max_length=30, verbose_name='Descripción')),
                ('municipio', models.ManyToManyField(blank=True, to='localidades.Municipio', verbose_name='Municipios')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
    ]
