# Generated by Django 2.2.5 on 2019-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='texto',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='texto',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
